// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBHDQBIs-sa3kaGuoPWTNARH_KDpXzM27s",
      authDomain: "testproject-77431.firebaseapp.com",
      databaseURL: "https://testproject-77431-default-rtdb.firebaseio.com",
      projectId: "testproject-77431",
      storageBucket: "testproject-77431.firebasestorage.app",
      messagingSenderId: "496587261194",
      appId: "1:496587261194:web:7f5e71e7a8f02bbf4426f3",
      measurementId: "G-WMG2QL3YRW"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Dj9033om0bZrNCEGet7kOxB_KYVcP04',
    appId: '1:496587261194:android:7c359ac539ad8db44426f3',
    messagingSenderId: '496587261194',
    projectId: 'testproject-77431',
    storageBucket: 'testproject-77431.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMoMC36XIROPj94ajqRocTpAsUeG18l_M',
    appId: '1:962680644755:ios:f54f24161e03ddbbff5966',
    messagingSenderId: '962680644755',
    projectId: 'testproject-77431',
    storageBucket: 'testproject-77431.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMoMC36XIROPj94ajqRocTpAsUeG18l_M',
    appId: '1:962680644755:ios:f54f24161e03ddbbff5966',
    messagingSenderId: '962680644755',
    projectId: 'testproject-77431',
    storageBucket: 'testproject-77431.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFAXVMap8O3jlopLi0D7-dH1LISA-SFw8',
    appId: '1:962680644755:web:673b2ebeb24898feff5966',
    messagingSenderId: '496587261194',
    projectId: 'brainbite-app',
    authDomain: 'brainbite-app.firebaseapp.com',
    storageBucket: 'brainbite-app.firebasestorage.app',
    measurementId: 'G-6WXG96TQ30',
  );
}
